remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "default"

title: "Hyojin Park"
name: "Hyojin Park"
description: "Developer Blog"
url: "https://bacococc.github.io"

repository: "bacococc/bacococc.github.io"

plugins:
  - jekyll-include-cache